version: '1'
services:
  web:
    restart: always
    build: .
    expose:
      - "80"
    command: gunicorn --bind 0.0.0.0:80 server:app --log-file -
    volumes:
      - .:/code
    ports:
      - "80:80"